export const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/icons/info.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "me.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-10 left-5",
      imageUrl: "/images/gallery/me/me.jpeg",
    },
    {
      id: 2,
      name: "casual-me.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-28 right-72",
      imageUrl: "images/contact/casual-me.jpeg",
    },
    {
      id: 3,
      name: "about-me.txt",
      icon: "/images/txt.png",
      kind: "file",
      fileType: "txt",
      position: "top-60 left-5",
      subtitle: "Meet the Developer Behind the Code",
      image: "/images/contact/aboutme.jpg",
      description: [
        "Hey! I'm Rafi, a software engineer who enjoys building powerful, efficient applications that actually solve real-world problems.",
        "I specialize in React, Next.js, Node.js, and Golang. My go-to stack for building fast, scalable, and reliable applications. I also use Docker to create consistent development environments and streamline deployment workflows.",
        "I'm passionate about clean architecture, maintainable code, and designing systems that remain easy to understand and scale as they grow. I enjoy solving complex technical challenges while keeping the developer experience simple.",
        "Outside of dev work, you'll probably find me tweaking my setup at 2AM, hunting for the perfect cup of coffee, or impulse-buying gadgets I've already convinced myself are 'essential' for my workflow.",
      ],
    },
  ],
};
