export const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "Trans Zigot",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-10 left-5",
      windowPosition: "top-[5vh] left-5",
      children: [
        {
          id: 1,
          name: "Zigot-Web.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Trans Zigot is a team of specialists committed to providing reliable car rental services at competitive and transparent prices.",
            "backed by comprehensive insurance, 24/7 customer support, as well as a fleet of well-maintained vehicles to ensure a comfortable, safe and satisfying rental experience.",
          ],
        },
        {
          id: 2,
          name: "zigot-web.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://mr-zigot-web.vercel.app/",
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "trans-zigot.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/work/trans-zigot-hero.png",
        },
        {
          id: 5,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "https://www.figma.com/design/H2rCrHG9sKMJ0eyweScT6V/Mr.-Zigot-Trans?node-id=1-185&t=MAHGYgCLW68fvTe9-1",
          position: "top-60 right-20",
        },
      ],
    },

    {
      id: 6,
      name: "Roomify",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-52 right-80",
      windowPosition: "top-[20vh] left-7",
      children: [
        {
          id: 1,
          name: "Roomify-Web.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 right-10",
          description: [
            "Roomify is an AI-powered architectural design platform that transforms 2D floor plans into realistic architectural visualizations in seconds.",
            "Built with React Router 7, TypeScript, Tailwind CSS, and Puter.js, it provides a seamless cloud-based workspace with secure authentication, real-time storage, and fast asset hosting.",
            "Designed for architects and designers, Roomify combines AI-driven rendering with an intuitive interface to streamline project management and accelerate the design workflow."
          ],
        },
        {
          id: 2,
          name: "roomify.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://roomify-build.vercel.app/",
          position: "top-20 left-20",
        },
        {
          id: 4,
          name: "roomify.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 left-80",
          imageUrl: "/images/work/roomify.png",
        },
      ],
    },

    {
      id: 7,
      name: "Fuel Management System",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[33vh] left-7",
      children: [
        {
          id: 1,
          name: "FMS.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Fuel Management System is a centralized web application developed for PT Presisi Digital Moderen Teknologi to monitor and manage fuel distribution across multiple operational sites from the head office.",
            "The system provides real-time visibility into fuel movement, helping improve operational efficiency, inventory control, and decision-making through a unified dashboard.",
            "Built with Next.js, React, and TypeScript on the frontend, and Golang, Fiber, GORM, and PostgreSQL on the backend, the application is fully containerized with Docker to ensure consistent deployment, scalability, and maintainability.",
            "Designed with a focus on performance, reliability, and clean architecture, the system enables seamless tracking of fuel transactions while supporting enterprise-scale operations.",
          ],
        },
        {
          id: 2,
          name: "fms.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://dashboard-mtgt.onrender.com",
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "fms.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/work/fms.png",
        },
        {
          id: 5,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "https://www.figma.com/design/HvSMO2xlQIe2YiHZ1WqjYk/PDMT?node-id=0-1&p=f&t=noj0lHaJufBWij8k-0",
          position: "top-60 right-20",
        },
      ],
    },

    {
      id: 8,
      name: "Ticketing Management System",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[33vh] left-7",
      children: [
        {
          id: 1,
          name: "TMS.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Ticketing Management System is a collaborative platform that enables site personnel to create and track support tickets while allowing head office teams and other site staff to monitor, collaborate, and resolve issues efficiently.",
            "Built with Flutter, Golang, Gin, GORM, Redis, MinIO, and Docker, the system delivers a scalable and reliable workflow for issue management.",
          ],
        },
        {
          id: 2,
          name: "tms.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "",
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "tms.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/work/tms.png",
        },
        {
          id: 5,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "https://www.figma.com/design/wpSNrP0uPYennxliq3UeQs/Untitled?t=noj0lHaJufBWij8k-0",
          position: "top-60 right-20",
        },
      ],
    },
  ],
};
