export const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "Trans Zigot Web",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-10 left-5",
      windowPosition: "top-[5vh] left-5",
      children: [
        {
          id: 1,
          name: "Zigot-Web.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "Trans Zigot is a team of specialists committed to providing reliable car rental services at competitive and transparent prices.",
            "backed by comprehensive insurance, 24/7 customer support, as well as a fleet of well-maintained vehicles to ensure a comfortable, safe and satisfying rental experience.",
          ],
        },
        {
          id: 2,
          name: "zigot-web.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://mr-zigot-web.vercel.app/",
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "trans-zigot.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/work/trans-zigot-hero.png",
        },
        {
          id: 5,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "https://www.figma.com/design/H2rCrHG9sKMJ0eyweScT6V/Mr.-Zigot-Trans?node-id=1-185&t=MAHGYgCLW68fvTe9-1",
          position: "top-60 right-20",
        },
      ],
    },

    {
      id: 6,
      name: "Roomify",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-52 right-80",
      windowPosition: "top-[20vh] left-7",
      children: [
        {
          id: 1,
          name: "Roomify-Web.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 right-10",
          description: [
            "",
          ],
        },
        {
          id: 2,
          name: "roomify.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "",
          position: "top-20 left-20",
        },
        {
          id: 4,
          name: "roomify.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 left-80",
          imageUrl: "/images/project-2.png",
        },
        {
          id: 5,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "",
          position: "top-60 left-5",
        },
      ],
    },

    {
      id: 7,
      name: "SubsTrack",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[33vh] left-7",
      children: [
        {
          id: 1,
          name: "SubsTrack.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "",
          ],
        },
        {
          id: 2,
          name: "substrack.com",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "",
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "substrack.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/images/project-3.png",
        },
        {
          id: 5,
          name: "Design.fig",
          icon: "/images/plain.png",
          kind: "file",
          fileType: "fig",
          href: "",
          position: "top-60 right-20",
        },
      ],
    },
  ],
};
